#!/bin/bash

################################################################################
# Analytics Validation Hook
# 
# Validates that all interactive HTML elements have proper analytics tracking.
# Prevents accidental commits of untracked interactive components.
#
# Usage:
#   .github/scripts/validate-analytics.sh          # Validate modified files
#   .github/scripts/validate-analytics.sh all      # Validate entire project
#
# Exit codes:
#   0 = All checks passed
#   1 = Violations found
################################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Counters for statistics
VIOLATIONS=0
FILES_CHECKED=0

# Temporary files for tracking violations
VIOLATIONS_FILE=$(mktemp)
trap "rm -f $VIOLATIONS_FILE" EXIT

################################################################################
# Utility Functions
################################################################################

log_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

log_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

log_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Check if a line contains an interactive element pattern
is_interactive_element() {
    local line="$1"
    
    # Match buttons, links, form elements, role="button", onclick attributes
    if [[ "$line" =~ \<button ]] || \
       [[ "$line" =~ \<a\ .*href ]] || \
       [[ "$line" =~ role=\"button\" ]] || \
       [[ "$line" =~ \<input.*type=\"submit\" ]] || \
       [[ "$line" =~ onclick= ]]; then
        return 0
    fi
    return 1
}

# Check if element should be excluded from tracking
should_exclude() {
    local line="$1"
    
    # Exclude internal navigation links (href="/..." or href="{{...BaseURL..." or href="|relLangURL")
    if [[ "$line" =~ href=\"/ ]] || \
       [[ "$line" =~ href=\"{{ ]] || \
       [[ "$line" =~ relLangURL ]] || \
       [[ "$line" =~ BaseURL ]]; then
        # But still track external links
        if ! [[ "$line" =~ href=\"http ]] && ! [[ "$line" =~ https:// ]]; then
            return 0  # Exclude this line
        fi
    fi
    
    # Exclude anchor links
    if [[ "$line" =~ href=\"# ]]; then
        return 0
    fi
    
    # Exclude disabled elements
    if [[ "$line" =~ disabled ]] || [[ "$line" =~ aria-disabled ]]; then
        return 0
    fi
    
    # Exclude hidden elements
    if [[ "$line" =~ display:none ]] || [[ "$line" =~ visibility:hidden ]] || [[ "$line" == *"hidden"* ]]; then
        return 0
    fi
    
    # Exclude elements with explicit opt-out
    if [[ "$line" =~ data-no-track ]]; then
        return 0
    fi
    
    # Exclude links without href attribute
    if [[ "$line" =~ \<a ]] && ! [[ "$line" =~ href= ]]; then
        return 0
    fi
    
    # Exclude rel="noopener noreferrer" (explicitly marked as not tracked)
    if [[ "$line" =~ noopener ]]; then
        return 0
    fi
    
    # Exclude button components generated by Hugo partial
    # Pattern: {{ partial "components/button.html" ... with trackingEvent
    if [[ "$line" =~ partial.*button.*trackingEvent ]]; then
        return 0
    fi
    
    # Exclude navigation menu items (role="none" indicates structural navigation)
    if [[ "$line" =~ role=\"none\" ]]; then
        return 0
    fi
    
    # Exclude only buttons with onclick that call internal component functions
    # Pattern: onclick="componentName()" but NOT onclick="alert(...)" or onclick="if (..."
    if [[ "$line" =~ onclick=\"[a-zA-Z_][a-zA-Z0-9_]*\(\)\" ]] && \
       ! [[ "$line" =~ onclick=\"window.open ]]; then
        return 0
    fi
    
    return 1  # Don't exclude
}

# Check if element has tracking attributes
has_tracking() {
    local line="$1"
    
    # Must have both data-event and data-event-label
    if [[ "$line" =~ data-event= ]] && \
       [[ "$line" =~ data-event-label= ]]; then
        return 0
    fi
    
    return 1
}

# Get line number from grep output
get_line_number() {
    local line="$1"
    # Extract line number from grep output (format: file:number:content)
    echo "$line" | cut -d':' -f2
}

################################################################################
# File Validation
################################################################################

validate_file() {
    local file="$1"
    local line_num=0
    local found_violations=0
    
    # Skip non-HTML files - only check actual template files
    if ! [[ "$file" =~ \.html$ ]]; then
        return 0
    fi
    
    # Skip test files (in test/ or tests/ directory, or .test. or .spec. in name)
    if [[ "$file" =~ ^test/ ]] || [[ "$file" =~ ^tests/ ]] || [[ "$file" =~ /test/ ]] || [[ "$file" =~ /tests/ ]] || [[ "$file" =~ \.test\. ]] || [[ "$file" =~ \.spec\. ]]; then
        return 0
    fi
    
    # Skip node_modules and build artifacts
    if [[ "$file" =~ /node_modules/|/public/|/resources/|/coverage/ ]]; then
        return 0
    fi
    
    # Skip backup and archive directories
    if [[ "$file" =~ \.backup\.|/_archived/|\.cody\.backup ]]; then
        return 0
    fi
    
    # Skip documentation files
    if [[ "$file" =~ /docs/|\.md$ ]]; then
        return 0
    fi
    
    FILES_CHECKED=$((FILES_CHECKED + 1))
    
    while IFS= read -r line; do
        ((line_num++))
        
        # Skip empty lines and comments
        [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
        
        # Check if this line contains an interactive element
        if is_interactive_element "$line"; then
            # Skip if it's in the exclude list
            if should_exclude "$line"; then
                continue
            fi
            
            # Check if it has tracking attributes
            if ! has_tracking "$line"; then
                found_violations=1
                VIOLATIONS=$((VIOLATIONS + 1))
                
                # Store violation for later reporting
                echo "$file:$line_num" >> "$VIOLATIONS_FILE"
                echo "$line" >> "$VIOLATIONS_FILE"
            fi
        fi
    done < "$file"
    
    return $found_violations
}

################################################################################
# Main Validation Logic
################################################################################

main() {
    local validate_all="${1:-}"
    local exit_code=0
    
    echo ""
    echo -e "${BLUE}🔍 ANALYTICS VALIDATION${NC}"
    echo -e "${BLUE}======================${NC}"
    echo ""
    
    # Determine which files to validate
    if [[ "$validate_all" == "all" ]]; then
        log_info "Validating entire project..."
        
        # Find all HTML/template files (excluding common directories)
        while IFS= read -r file; do
            validate_file "$file" || exit_code=1
        done < <(find . -type f \( -name "*.html" -o -name "*.md" \) \
            ! -path "./node_modules/*" \
            ! -path "./public/*" \
            ! -path "./resources/*" \
            ! -path "./coverage/*" \
            ! -path "./.cody/*" \
            ! -path "./test/*" \
            ! -path "./tests/*" \
            ! -path "*/.test.*" \
            ! -path "*/.spec.*" \
            2>/dev/null)
    else
        log_info "Validating modified files..."
        
        # Get modified files from git
        local modified_files
        if git rev-parse --verify HEAD >/dev/null 2>&1; then
            # Staged and unstaged changes
            modified_files=$(git diff --name-only --cached --diff-filter=ACMU 2>/dev/null || echo "")
            modified_files="$modified_files $(git diff --name-only --diff-filter=ACMU 2>/dev/null || echo "")"
        else
            # Initial commit
            modified_files=$(git diff --name-only --cached --diff-filter=ACMU 2>/dev/null || echo "")
        fi
        
        if [[ -z "$modified_files" ]]; then
            log_success "No modified files to validate"
            echo ""
            return 0
        fi
        
        # Validate each modified file
        while IFS= read -r file; do
            [[ -z "$file" ]] && continue
            [[ ! -f "$file" ]] && continue
            
            validate_file "$file" || exit_code=1
        done < <(printf '%s\n' $modified_files)
    fi
    
    # Report results
    echo ""
    echo -e "${BLUE}📊 VALIDATION SUMMARY${NC}"
    echo -e "${BLUE}===================${NC}"
    echo "Files checked: $FILES_CHECKED"
    echo "Violations found: $VIOLATIONS"
    echo ""
    
    if [[ $VIOLATIONS -gt 0 ]]; then
        log_error "Analytics Validation Failed"
        echo ""
        echo -e "${RED}📍 Missing data-event attributes:${NC}"
        echo ""
        
        # Parse and display violations with context
        local current_file=""
        while IFS= read -r line; do
            if [[ "$line" =~ ^[^:]+:[0-9]+$ ]]; then
                # This is the file:line_number line
                current_file="$line"
                echo "  $current_file"
            else
                # This is the code line
                # Strip leading/trailing whitespace and truncate if too long
                local code=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | cut -c1-100)
                echo "    $code"
            fi
        done < "$VIOLATIONS_FILE"
        
        echo ""
        echo -e "${YELLOW}📋 Allowed exceptions:${NC}"
        echo "  • Internal navigation links (href=\"/...\")"
        echo "  • Anchor links (href=\"#...\")"
        echo "  • Disabled elements (disabled attribute or aria-disabled=\"true\")"
        echo "  • Hidden elements (display:none, visibility:hidden, hidden attribute)"
        echo "  • Explicit opt-out (data-no-track attribute)"
        echo "  • Links without href attribute"
        echo ""
        echo -e "${YELLOW}ℹ️  How to fix:${NC}"
        echo "  1. Add data-event attribute:"
        echo "     <button data-event=\"button_click\" data-event-label=\"Label\">Text</button>"
        echo ""
        echo "  2. OR use the button component:"
        echo "     {{ partial \"components/button.html\" (dict \"trackingEvent\" \"event_name\") }}"
        echo ""
        echo "  3. OR mark as excluded:"
        echo "     <button data-no-track>Internal Button</button>"
        echo ""
        echo -e "${BLUE}📖 See: docs/development/FEATURE_DEVELOPMENT_CHECKLIST.md${NC}"
        echo ""
        echo -e "${YELLOW}💡 To bypass this check (not recommended):${NC}"
        echo "    git push --no-verify"
        echo ""
        
        return 1
    else
        log_success "All interactive elements have proper analytics tracking"
        echo ""
        return 0
    fi
}

################################################################################
# Script Entry Point
################################################################################

main "$@"
exit $?
