/**
 * Example: Integrating ValidationResult with HugoIntegration
 *
 * This example shows how to use ValidationResult to validate
 * content generated by HugoIntegration before finalizing.
 */

import { HugoIntegration } from '../../core/hugo-integration.js';
import { ValidationResult } from '../validation.js';
import type { ContentType } from '../../types/index.js';

/**
 * Example: Generate and validate a blog post
 */
export async function generateAndValidateBlog() {
  const hugo = new HugoIntegration();
  const validator = new ValidationResult();

  // 1. Generate blog content
  const result = await hugo.generateContentBundle({
    type: 'blog',
    title: 'Test Blog Post',
    date: new Date('2025-01-15'),
    draft: true,
    frontmatter: {
      summary: 'This is a test blog post summary that is long enough to pass validation requirements.',
      tags: ['test', 'blog'],
      categories: ['testing'],
      content_type: 'tutorial',
    },
    content: '# Test Blog Post\n\nThis is test content.',
  });

  console.log('Generated content at:', result.path);

  // 2. Validate the generated content
  const validation = await validator.validateContent('blog', result.directory);

  if (validation.success) {
    console.log('✅ Content validated successfully');
    console.log('Content ready for review and deployment');
  } else {
    console.log('❌ Validation failed:');
    validation.errors.forEach(error => console.log(`  - ${error}`));
    if (validation.warnings.length > 0) {
      console.log('⚠️  Warnings:');
      validation.warnings.forEach(warning => console.log(`  - ${warning}`));
    }
  }

  return validation;
}

/**
 * Example: Dry-run validation before generating content
 */
export async function validateBeforeGenerate() {
  const validator = new ValidationResult();

  const content = `---
title: "Test Blog Post"
date: "2025-01-15"
summary: "A summary that meets the minimum length requirements for validation"
draft: true
tags: ["test"]
categories: ["testing"]
---

# Test Blog Post

Content here.
`;

  // Validate before writing to disk
  const result = await validator.validateDryRun('blog', content);

  if (result.success) {
    console.log('✅ Content structure is valid');
    console.log('Safe to generate the content bundle');
  } else {
    console.log('❌ Content structure has errors:');
    result.errors.forEach(error => console.log(`  - ${error}`));
  }

  return result;
}

/**
 * Example: Validate existing portfolio item
 */
export async function validateExistingPortfolio() {
  const validator = new ValidationResult();

  // Validate an existing portfolio project
  const result = await validator.validatePortfolio(
    '/Users/peter/github/pwarnock.github.io/content/portfolio/example-project'
  );

  console.log('Validation result:', validator.formatResult(result));

  return result;
}

/**
 * Example: Integration with content generation workflow
 */
export async function contentGenerationWorkflow() {
  const hugo = new HugoIntegration();
  const validator = new ValidationResult();

  const workflows: Array<{ type: ContentType; title: string }> = [
    { type: 'blog', title: 'My First Blog Post' },
    { type: 'portfolio', title: 'Amazing Project' },
    { type: 'tech-radar', title: 'New Technology Tool' },
  ];

  const results = [];

  for (const workflow of workflows) {
    console.log(`\nProcessing ${workflow.type}: ${workflow.title}`);

    // Generate content bundle
    const bundle = await hugo.generateContentBundle({
      type: workflow.type,
      title: workflow.title,
      date: new Date(),
      draft: true,
      frontmatter: getFrontmatterForType(workflow.type),
    });

    console.log(`Generated: ${bundle.path}`);

    // Validate content
    const validation = await validator.validateContent(workflow.type, bundle.directory);

    if (validation.success) {
      console.log('✅ Validated successfully');
    } else {
      console.log('❌ Validation failed:');
      validation.errors.forEach(error => console.log(`  - ${error}`));
    }

    results.push({
      type: workflow.type,
      title: workflow.title,
      path: bundle.path,
      valid: validation.success,
      errors: validation.errors,
      warnings: validation.warnings,
    });
  }

  return results;
}

/**
 * Helper: Get frontmatter template for content type
 */
function getFrontmatterForType(type: ContentType): Record<string, any> {
  switch (type) {
    case 'blog':
      return {
        summary: 'A comprehensive blog post about an interesting topic that provides value to readers.',
        tags: ['blog', 'example'],
        categories: ['general'],
      };

    case 'portfolio':
      return {
        description: 'A detailed description of the portfolio project.',
        client: 'Example Client',
        technologies: ['React', 'TypeScript', 'Node.js'],
        completion_date: '2025-01',
        category: 'Web App',
        github_url: 'https://github.com/example/project',
        live_url: 'https://example-project.com',
      };

    case 'tech-radar':
      return {
        description: 'An innovative tool for solving complex problems.',
        quadrant: 'tools',
        ring: 'adopt',
        tags: ['innovation', 'productivity'],
      };

    default:
      return {};
  }
}

// Export examples for use in other modules
export {
  generateAndValidateBlog as example1,
  validateBeforeGenerate as example2,
  validateExistingPortfolio as example3,
  contentGenerationWorkflow as example4,
};
