name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Test build
      run: |
        if [ ! -d "public" ]; then
          echo "Build failed: public directory not found"
          exit 1
        fi
        echo "Build successful"

    - name: HTML validation
      uses: chabad360/htmlproofer@master
      with:
        directory: "./public"
        allow_hash_href: true
        check_external_hash: true
        check_html: true
        check_img_http: true
        check_opengraph: true
        validation: true